task_name: boundary_single_timestep_1_box_augmented
batch_size: 16
eval_batch_size: 32
rotation_batch_size: 32
epochs: 5000
loss_type: 'L1' # 'L1' or 'L2'
learning_rate: 0.0003
save_interval: 100
validation_interval: 20
memorization_test: False
track_oct_equivariance_error: False
track_so3_equivariance_error: False
train_aug_group: 'oct' # change to 'oct' for octahedral data augmentation
val_aug_group: null
test_aug_group: null
seed: 42

dataset:
  input_prefix: channel_nearwall_filtered_fs4
  target_prefix: channel_nearwall
  boxes: [0] # [0] or [0,1,2]
  train_split: 0.667 # time series will be split sequentially into train, val, test sets
  val_split: 0.2
  test_split: 0.133
  train_samples: 1 # e.g. 1, 10, 20, or 'all'. Subsamples the training portion of the time series.
  val_samples: 'all'
  test_samples: 'all'
  sampling_method: 'sequential' # 'random' or 'sequential', only applies if time_samples is not 'all'. Sequential starts from 0

model:
  model_type: MultiScaleSR
  is_3d: True
  hidden_channels: 128
  upscale_factor: 4
  input_channels: 3
  output_channels: 3